name: farmerApp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.0
  geoflutterfire: ^2.2.1
  flutter_spinkit: "^4.1.2"
  google_maps_flutter: ^1.2.0
  location: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf